/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package di.uniba.map.b.adventure.interfacee;

import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author gruppo 'Le bimbe di Luca'
 */
public class Inizio extends javax.swing.JFrame {

    PrintWriter out;
    /**
     * Creates new form Inizio
     * @param out
     */
    // Costruttore
    public Inizio( PrintWriter out ) {
        initComponents();
        init();
        this.out = out;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImage = new javax.swing.JLabel();
        jButtonIniziaPartita1 = new javax.swing.JButton();
        jButtonEsci = new javax.swing.JButton();
        jButtonCaricaPartita = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemAboutUs = new javax.swing.JMenuItem();
        jMenuItemAboutGame = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PianetaGame");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Agency FB", 1, 10)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));
        setIconImage((new ImageIcon(".\\src\\main\\java\\di\\uniba\\map\\b\\adventure\\resources\\logo.jpeg")).getImage());
        setResizable(false);

        jLabelImage.setIcon(new ImageIcon(".\\src\\main\\java\\di\\uniba\\map\\b\\adventure\\resources\\Spazio.png"));
        jLabelImage.setOpaque(true);

        jButtonIniziaPartita1.setBackground(new java.awt.Color(0, 0, 255));
        jButtonIniziaPartita1.setFont(new java.awt.Font("Gabriola", 3, 20)); // NOI18N
        jButtonIniziaPartita1.setText("Inizia Partita");
        jButtonIniziaPartita1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        jButtonIniziaPartita1.setOpaque(false);
        jButtonIniziaPartita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniziaPartita1ActionPerformed(evt);
            }
        });

        jButtonEsci.setBackground(new java.awt.Color(51, 51, 255));
        jButtonEsci.setFont(new java.awt.Font("Gabriola", 3, 20)); // NOI18N
        jButtonEsci.setText("Esci");
        jButtonEsci.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        jButtonEsci.setOpaque(false);
        jButtonEsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEsciActionPerformed(evt);
            }
        });

        jButtonCaricaPartita.setFont(new java.awt.Font("Gabriola", 3, 20)); // NOI18N
        jButtonCaricaPartita.setText("Carica Partita");
        jButtonCaricaPartita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        jButtonCaricaPartita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaricaPartitaActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenuAbout.setForeground(new java.awt.Color(51, 51, 255));
        jMenuAbout.setText("About");

        jMenuItemAboutUs.setText("About Us");
        jMenuItemAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutUsActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemAboutUs);

        jMenuItemAboutGame.setText("About Game");
        jMenuItemAboutGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutGameActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemAboutGame);

        jMenuBar1.add(jMenuAbout);

        jMenuHelp.setForeground(new java.awt.Color(51, 51, 255));
        jMenuHelp.setText("Help");

        jMenuItemHelp.setText("Help comandi");
        jMenuHelp.add(jMenuItemHelp);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButtonIniziaPartita1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonCaricaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCaricaPartita, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonIniziaPartita1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonEsci, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsciActionPerformed
        // TODO add your handling code here:
        int option;
        option = JOptionPane.showConfirmDialog(this, "Sei sicuro di voler chiudere il gioco?", "Uscita gioco", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            out.println("quit");
            this.dispose();
        }
    }//GEN-LAST:event_jButtonEsciActionPerformed

    private void jButtonIniziaPartita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniziaPartita1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        out.println("new");
        this.dispose();
    }//GEN-LAST:event_jButtonIniziaPartita1ActionPerformed

    private void jButtonCaricaPartitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaricaPartitaActionPerformed
        // TODO add your handling code here:
        out.println("load");
        this.dispose();
    }//GEN-LAST:event_jButtonCaricaPartitaActionPerformed

    private void jMenuItemAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutUsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "- Pianeta Game -\n"
                + "Autori: Luca Serio, Raffaella Nasca, Rosalba Nardiello \n"
                , "Pianeta Game", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(".\\src\\main\\java\\di\\uniba\\map\\b\\adventure\\resources\\logo.jpeg"));
    }//GEN-LAST:event_jMenuItemAboutUsActionPerformed

    private void jMenuItemAboutGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutGameActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "**** Adventure Luca, Rosalba, Raffaella ****\n\n"
                + "Il protagonista, Capitan Hector, si trova \n"
                + "nella Navicella B612 della galassia Reggy e sta per \n"
                + "tornare nel suo pianeta nativo: Blind. Per cause oscure,\n"
                + "perde il controllo della navicella e di tutti i suoi \n"
                + "comandi e per salvarsi dovra' completare le missioni \n"
                + "nelle varie stanze.\n"
                + "Buon Divertimento!\n",
                "Pianeta Game", JOptionPane.INFORMATION_MESSAGE, new ImageIcon(".\\src\\main\\java\\di\\uniba\\map\\b\\adventure\\resources\\logo.jpeg"));
    }//GEN-LAST:event_jMenuItemAboutGameActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inizio().setVisible(true);
            }
        });
    }*/
    
    private void init () {
        //jLabelImage.setIcon(new javax.swing.ImageIcon(".\\src\\main\\java\\di\\uniba\\map\\b\\adventure\\resources\\Spazio.png");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaricaPartita;
    private javax.swing.JButton jButtonEsci;
    private javax.swing.JButton jButtonIniziaPartita1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAboutGame;
    private javax.swing.JMenuItem jMenuItemAboutUs;
    private javax.swing.JMenuItem jMenuItemHelp;
    // End of variables declaration//GEN-END:variables
}
